### ISSUE TITLE
create table

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#1]
# Value Proposition

**As a** User
**I want to** add my running data to a table
**So that** I have a structured overview

# Description

<a href="https://ibb.co/CQSt5Bv"><img src="https://i.ibb.co/njK0srf/Screenshot-2022-08-15-at-13-21-32.png" alt="Screenshot-2022-08-15-at-13-21-32" border="0"></a>

# Acceptance Criteria

- [ ] A table for the running data is displayed
- [ ] A form accepts user input for all 5 data points
- [ ] Validity checks for inputs
- [ ] A button for adding a new run is displayed

# Tasks

- [x] Add a new branch
- [x] Create a Table Component with 5 columns
- [ ] Create a form with 5 input fields for all 5 data points
- [ ] Create validity checks for every input field
  - [ ] Distance - only positive decimals
  - [ ] Pace - format: mm:ss
  - [ ] Time - format: hh:mm:ss
  - [ ] Borg - Min. 0, max. 10
  - [ ] Pain - Min. 0, max. 5
- [ ] Create a Submit Button, which adds the data to the table
  - [ ] add `event.preventDefault()`
- [ ] Rows will be added automatically on newly submitted data
- [ ] Add 3 dummy data-sets to cultivate the table

# Complexity

L

**Comment by Gw3i** [comment]
Really good #1 User Story!

**Comment by ahohnsen** [comment]
Hey Joschka,

Nicely done 💪🏼 I have a few suggestions:

In your scribble it looks like you are using placeholder text inside your inputs instead of labels. I strongly suggest to use label elements for all input fields. You would then need to adjust your scribble to make clear that these should be labels.
In your acceptance criteria you do not need to write what is already visible in your scribble 🙂 
Instead of writing _"Validity checks for inputs"_ it would be better to specify which validation checks you mean e.g. all input fields are required.
As well, you could mention in your acceptance criteria if your page is scrollable 🙂
