### ISSUE TITLE
Implement Zustand

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#10]
# Value Proposition

**As a** Developer
**I want to** use useStore
**So that** I can access userData more easily in any component

# Description

`UseStore()` makes entered userData easily accessible from anywhere inside the app, plus it makes it easy to use localStorage via persist to keep entered userData after browser refresh.

# Acceptance Criteria

- [x] Zustand is implemented
- [x] One array with mock-data is declared within Zustand
- [x] Submitted data via `RunDataForm` is saved in Zustand

# Tasks

- [x] Add a new branch
- [x] Setup Zustand
- [x] Move mock-data from `mock-data.json` to Zustand
- [x] Setup AddRun-function within Zustand --> `RunDataForm` sends data to Zustand

# Complexity

L
