### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#11]
# Value Proposition

**As a** User
**I want to** have buttons to access different pages 
**So that** I have a more structured/ordered overview over my data

# Description

<a href="https://ibb.co/9YbsqPj"><img src="https://i.ibb.co/bdszrtn/Screenshot-2022-09-01-at-00-48-53.png" alt="Screenshot-2022-09-01-at-00-48-53" border="0"></a>

# Acceptance Criteria

- [x] A footer bar is displayed with links that lead to the respective page on click

# Tasks

(for developers team)

- [x] start a new branch
- [x] create footer bar
- [x] create 2 pages
  - [x] Home
  - [x] Run Protocol (Shows table with entered run data)
- [x] Create Link Components that send the user to the respective page on click.

# Complexity

M
