### ISSUE TITLE
Header + Profile Icon

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#13]
# Value Proposition

**As a** User
**I want to** have a clickable profile icon in the header 
**So that** I know where I have to click to find more options

# Description

<a href="https://ibb.co/F7zwzQ3"><img src="https://i.ibb.co/GPR2RZp/Screenshot-2022-09-01-at-01-05-16.png" alt="Screenshot-2022-09-01-at-01-05-16" border="0"></a>

# Acceptance Criteria

- [ ] A header is displayed with a profile icon
- [ ] On click on the profile icon, a side pane opens up

# Tasks

(for developers team)

- [ ] start a new branch
- [ ] create a header
- [ ] add a profile icon
  - [ ] a side pane opens on click

# Complexity

L

**Comment by ckskr** [comment]
Do you already know what happens in the side pane? You could add some words about that as this is very important to the user.

**Comment by j-eick** [comment]
@ckskr The side pane will contain a few further functions like 
- new workout
- new run

I want to have that extra space to not clutter the navbar with too many icons.
