### ISSUE TITLE
Diagram shows the most recent 7 runs

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#15]
# Value Proposition

**As a** User
**I want to** see a max. number of 7 runs in the diagram
**So that** the diagram is still easy to read

# Description
The diagram could potentially show a huge number of datapoints, but in order to make it easy to read and to keep it "good for the eyes" the max number of datapoints should be limited to 7. 

# Acceptance Criteria

- [x] The diagram shows a maximum number of 7 run entries
- [x] The diagram shows the most recent 7 runs and self-actualises itself, when a new run is added

# Tasks

(for developers team)

- [x] create new branch
- [x] Make the diagram show the last 7 run entries

# Complexity

M
