### ISSUE TITLE
Profile icon + open sidepane

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#16]
# Value Proposition

**As a** User
**I want to** have a clickable profile icon in the header 
**So that** I know where I have to click to find more options

# Description

<a href="https://ibb.co/F7zwzQ3"><img src="https://i.ibb.co/GPR2RZp/Screenshot-2022-09-01-at-01-05-16.png" alt="Screenshot-2022-09-01-at-01-05-16" border="0"></a>

# Acceptance Criteria

- [ ] On click on the profile icon inside the header, a side pane opens up

# Tasks

(for developers team)

- [ ] start a new branch
- [ ] a side pane opens on click on the profile icon

# Complexity

M
