### ISSUE TITLE
RunForm is shown on button click

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#18]
# Value Proposition

**As a** User
**I want to** see a button below the diagram
**So that** I know where to press in order to add a new run

# Description

<a href="https://ibb.co/8McLQ88"><img src="https://i.ibb.co/zsJTtff/Screenshot-2022-09-06-at-00-38-26.png" alt="Screenshot-2022-09-06-at-00-38-26" border="0"></a>

# Acceptance Criteria

- [x] on click on the AddRun-Button, a form field shows up
- [x] on click on the AddRun-Button, the button turns into a cancel-symbol
- [x] on click of the submit button, the entered data is shown in the diagram

# Tasks

(for developers team)

- [x] start a new branch
- [x] add AddRun-button below diagram
  - [x] on click: form shows
  - [x] while form shows, the AddRun-button turns into an "undo" button"
- [x] added data gets visualized in the diagram

# Complexity

M
