### ISSUE TITLE
New page for adding workouts

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#19]
# Value Proposition

**As a** User
**I want to** be able to create my own workout-sessions on a separate page
**So that** I can customize my training

# Description

<a href="https://imgbb.com/"><img src="https://i.ibb.co/F7RvGsM/Screenshot-2022-09-04-at-13-23-15.png" alt="Screenshot-2022-09-04-at-13-23-15" border="0"></a>

# Acceptance Criteria

- [ ] a new page can be accessed through an additional icon in the navbar
- The new page...
  - [ ] has a title
  - [ ] shows a dropdown menu with 5 options to choose from
  - [ ] shows an optional "+ button", that adds a new dropdown menu to extend the workout
- [ ] a "next step"-button is displayed. Its function will be added in the next Userstory.

# Tasks

(for developers team)

- [ ] start a new branch
- [ ] add a new icon to the navbar,
  - [ ] on click: a new page is shown
- [ ] add a form to the new page
  - [ ] add dropdown 
    - [ ] Warmup
    - [ ] Core
    - [ ] Torso
    - [ ] Legs
    - [ ] HIT
  - [ ] add "+" button
    - [ ] onClick( ) another dropdown will be added
  - [ ] add "Next step" button

# Complexity

L
