### ISSUE TITLE
create table

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#2]
# Value Proposition

**As a** User
**I want to** add my running data to a table
**So that** I have a structured overview

# Description

<a href="https://ibb.co/7VHcYSn"><img src="https://i.ibb.co/NpXhVF9/Screenshot-2022-08-19-at-15-15-27.png" alt="Screenshot-2022-08-19-at-15-15-27" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>13 картинки</a><br />

# Acceptance Criteria

- [x] A table for the running data is displayed
- [x] A form accepts user input for all 5 data points
- [x] Validity checks for inputs
  - [x] Distance - only positive decimals
  - [x] Pace - format: mm:ss
  - [x] Time - format: hh:mm:ss
  - [x] Borg - Min. 0, max. 10
  - [x] Pain - Min. 0, max. 5
- [x] Only time-input is required
- [x] A button for adding a new run is displayed
- [x] A submit button is displayed
  - [x]  Submitted input information is displayed in the table
- [x] Error Message indicates when user makes an input outside the respective scope.
 

# Tasks

- [x] Add a new branch
- [x] Create a Table Component with 5 columns
- [x] Create a form with 5 input fields for all 5 data points
  - [x] Input fields are labelled "distance", "time", "pace", "borg", "pain"
- [x] Create validity checks for every input field (see AC)
- [x] Create a Submit Button, which adds the data to the table
  - [x] add `event.preventDefault()`
- [x] Rows will be added automatically on newly submitted data
- [x] Add 3 dummy data-sets to cultivate the table
- [x] Create an error message for wrong inputs

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Joschka,

Great job 👍🏼 
In the acceptance criteria it would be good to specify what happens when the user clicks the submit button. I assume the data will be added to the table. But maybe the user will also be redirected somewhere or if he/she stays on the same page will all the input fields be reset? 🙂
