### ISSUE TITLE
Table allows deletion of entries

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#21]
# Value Proposition

**As a** User
**I want to** be able manipulate my entries
**So that** I can correct my entries

# Description

<a href="https://imgbb.com/"><img src="https://i.ibb.co/TkGwNpY/Screenshot-2022-09-06-at-11-28-59.png" alt="Screenshot-2022-09-06-at-11-28-59" border="0"></a>

# Acceptance Criteria

- [x] Table-Row is clickable
- [x] On click two buttons appear
  - [x] Delete
- [x] On click of the respective button, changes can be made and the table gets updated

# Tasks

(for developers team)

- [x] start a new branch
- [x] create button delete + respective function in useStore
- [x] make rows clickable
  - [x] on click the delete button is displayed
  - [x] clicking the respective button calls the respective function
  - [x] Delete: The entire entry disappears
 - [x] After making use of delete the table shows one less entry

# Complexity

M
