### ISSUE TITLE
Table allows editing of entries

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#24]
# Value Proposition

**As a** User
**I want to** be able manipulate my entries
**So that** I can correct my entries

# Description

<a href="https://imgbb.com/"><img src="https://i.ibb.co/rbLkkmJ/Screenshot-2022-09-07-at-17-39-46.png" alt="Screenshot-2022-09-07-at-17-39-46" border="0"></a>

# Acceptance Criteria

- [ ] On click of the row an edit buttons appears
- [ ] On click of the button, entry-changes can be made and the table gets updated

# Tasks

(for developers team)

- [ ] start a new branch
- [ ] create edit-button + respective function in useStore
- [ ] After making use of the edit-button the Table shows the updated data

# Complexity

m
