### ISSUE TITLE
add index-column to table

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#3]
# Value Proposition

**As a** User
**I want to** see the index of a respective list-entry
**So that** I can see at first glance that this was my x-th run.

# Description

<a href="https://ibb.co/cy68SGN"><img src="https://i.ibb.co/XW75rhz/Screenshot-2022-08-16-at-11-34-10.png" alt="Screenshot-2022-08-16-at-11-34-10" border="0"></a>

# Acceptance Criteria

- [ ] an additional table column shows the index of the respective row
- [ ] the index increments automatically with every added entry

# Tasks

(for developers team)

- [ ] add another `th` and `td` to the `.map()`-function
- [ ] adjust the `.map()`-function in order to show the index

# Complexity

S

**Comment by ahohnsen** [comment]
Nice little user story. 🙂 I think it would be nice if the scribble would show already the final state, so the table with the column for the index.

As well I would suggest to always show the scribble of your whole app/screen instead of only little parts of it. So it is easy to see how the product should look after this user story.

**Comment by j-eick** [comment]
@ahohnsen Roger that. 🫡 Will consider that in my next stories.
