### ISSUE TITLE
add date to table

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#4]
# Value Proposition

**As a** User
**I want to** see the date in the table
**So that** I know how I ran on which day

# Description

<a href="https://ibb.co/FWQ5m6g"><img src="https://i.ibb.co/j5Cybhg/Screenshot-2022-08-17-at-17-36-18.png" alt="Screenshot-2022-08-17-at-17-36-18" border="0"></a>

# Acceptance Criteria

- [ ] The form has an option to input the date
- [ ] The date that was added is displayed inside the table

# Tasks

(for developers team)

- [ ] create new branch
- [ ] add new input inside existing form
  - [ ] add a label
- [ ] modify .map() according to this change, so that another `td` will be added to the table
- [ ] add input-format validation

# Complexity

XS, S, M, L, XL
