### ISSUE TITLE
turn input into dropdown

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#7]
# Value Proposition

**As a** User
**I want to** use a dropdown
**So that** I can pick a value more easily

# Description

<a href="https://ibb.co/2Z6J2bx"><img src="https://i.ibb.co/DrbdXqh/Screenshot-2022-08-19-at-11-47-05.png" alt="Screenshot-2022-08-19-at-11-47-05" border="0"></a>

# Acceptance Criteria

- [ ] A dropdown menu is displayed that shows available options upon clicking it. 
 _💡 For preview purposes the "..." in the scribble indicates, that list of options continues until "10"._
- [ ] The chosen value will be shown in the table after clicking the submit button

# Tasks

(for developers team)

- [ ] start a new branch
- [ ] create a dropdown menu with 
  - [ ] 10 options for borg: 1 - 10
  - [ ] 11 options for pain: 0 - 10
- [ ] picked numbers will be added to the table

# Complexity

m

**Comment by RobertBReich** [comment]
"We are the borg, resistance is futile!"

Öhm... What is this "borg" thing? 😂
Other than that the AC and Tasks are looking good.

cheers
R.

**Comment by j-eick** [comment]
> "We are the borg, resistance is futile!"
> 
> Öhm... What is this "borg" thing? 😂 Other than that the AC and Tasks are looking good.
> 
> cheers R.

The "borg" value indicates the perceived intensity the athlete experienced during the run. When he later decides to look over his past runs, he knows how much effort he had to give.
