### ISSUE TITLE
Turn Table into Diagram

### ISSUE THREAD

**Issue by j-eick** [j-eick/capstone-project#8]
# Value Proposition

**As a** User
**I want to** see my data in a diagram
**So that** I can judge my progress with one glance

# Description

<a href="https://ibb.co/2SF4Bsj"><img src="https://i.ibb.co/T1w35bH/Screenshot-2022-08-22-at-10-15-15.png" alt="Screenshot-2022-08-22-at-10-15-15" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>13 картинки</a><br />

# Acceptance Criteria

- [x] A diagram is displayed that visualises the data that was put into the table
- [x] The diagram replaces the table (mid-term)

# Tasks

(for developers team)

- [x] start a new branch
- [x] implement chart.js

# Complexity

L

**Comment by UniversalTraveller** [comment]
Hello Josh! I'd use a different value proposition. Actually, this user story is not about adding value for the developer, like for example refactoring code would be. It's about adding value for the user. A good value proposition could be something like this:

As a user
I want to see my data in a diagram
So that I can judge my progress instantly

**Comment by j-eick** [comment]
Thanks @UniversalTraveller ! 
Done ✅
